name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: .

    - name: Debug runner environment
      run: |
        echo "PWD: $(pwd)"
        echo "Listing repository root contents:"; ls -la
        echo "Contents of project folder:"; ls -la MLAppTensorflow || true
        dotnet --info
      working-directory: .

    - name: Build
      run: dotnet build
      working-directory: .

    - name: Setup Python for smoke test
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Run smoke test
      run: |
        chmod +x scripts/smoke_test.sh
        ./scripts/smoke_test.sh
      working-directory: .